@HOST=http://localhost:3000

### User
GET {{HOST}}/users

### User
GET {{HOST}}/users/username/test001@test.com

### Create User
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "test002",
  "email": "test002@test.com"
}