@HOST=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QwMDFAdGVzdC5jb20iLCJzdWIiOiIwODFjN2JlYi1jYzcxLTRlZWEtYmMyZi1hMjY1OTMzOGRmODYiLCJpYXQiOjE3NTc0Mjk4MTIsImV4cCI6MTc1NzQyOTg3Mn0.0Io3haDll8Gcf0rOGDZeDYhYh3p4q-RsPtUekUY7AlA

### Get Proile
GET {{HOST}}/profile
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Auth Login
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "username": "test001@test.com",
  "password": "abc123"
}

### Auth Logout
POST {{HOST}}/auth/logout
Content-Type: application/json

### SignUp
POST {{HOST}}/auth/signup
Content-Type: application/json

{
  "email": "test001@test.com",
  "password": "Crm123!@#"
}

### Login
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "username": "test001@test.com",
  "password": "Crm123!@#"
}